### ISSUE TITLE
get-members-of function doesn't include the input node

### ISSUE THREAD

**Issue by Habush** [singnet/pln#20]
In the `get-members-of` function defined in [extensional-utils.scm](https://github.com/singnet/pln/blob/e884b9355e94c7a4dd7339b9b1d2b6f9f12b8e2f/opencog/pln/rules/extensional/extensional-utils.scm#L22), it returns an empty list if the input has no atoms that have `MemberLink` connection to it. But from basic set theory, any set is considered to be a subset of itself. Hence, the input atom should be included in the result.

This becomes more important when trying to create `SubsetLink`s from `MemberLink`s using pln. For example, in the bio-atomspace we have the following relationship between Genes & [Pathways](https://en.wikipedia.org/wiki/Biological_pathway):

```
(Member (stv 1 1) (Gene "A") (Reactome "R1"))

(Member (stv 1 1) (Gene "B") (Reactome "R1"))

(Member (stv 1 1) (Gene "A") (Reactome "R2"))

(Member (stv 1 1) (Gene "C") (Reactome "R3"))
```

The [subset-direct-introduction](https://github.com/singnet/pln/blob/e884b9355e94c7a4dd7339b9b1d2b6f9f12b8e2f/opencog/pln/rules/extensional/subset-direct-introduction.scm#L16) rule doesn't generate a `SubsetLink` between the genes and pathways because `get-members-of` function returns an empty list for the genes which results in the confidence of the stv to be 0.

**Comment by ngeiswei** [comment]
> The subset-direct-introduction rule doesn't generate a SubsetLink between the genes and pathways

But my understanding is that genes and pathways do not have members in common, right? If so it shouldn't create subset links indeed (or it could but the tv strength should be null).

> from basic set theory, any set is considered to be a subset of itself

Good point, so if you need you could generate that knowledge

```
(Subset (stv 1 1)
  A
  A)
```

from a different rule (cause `subset-direct-introduction` is based on direct evidence, but such a rule is more abstract and can by-pass direct evidence). So if needed you can introduce a rule for it (I don't think there is one, though perhaps check in the `wip` folder just in case. I didn't write most of the rules in that folder, BTW, which is why I don't even know it that well). I think a good place would be `rules/proposition`, and a good name would be `subset-reflexivity-introduction`, and its semi-formal definition would be

```
A
|-
(Subset (stv 1 1)
  A
  A)
```

**Comment by Habush** [comment]
> But my understanding is that genes and pathways do not have members in common, right? 

If a gene G is a member of a pathways P then the common member between the two is gene G itself. (i.e G ∩ P = G) and if G is not member of P then they don't have common members. Here, I'm considering all genes as a sets with cardinality of 1 and the pathways as sets of n genes (n > 1).  Hence, it should create a subset links between the genes and the pathways.

**Comment by ngeiswei** [comment]
> Hence, it should create a subset links between the genes and the pathways.

Strictly speaking it should be subset links between gene singletons and pathways.
